feat: Added user routes
attech-org/leleka-backend pull request #10
Opened 2022-08-26 16:02 UTC by AndrewKaenko

Added user routes

2022-08-26 16:28 UTC, NikPaukov requested changes

2022-08-26 16:28 UTC, NikPaukov commented on src/services/user.service.ts
> +    throw new Error("Error");
should be more detalised errors)
```suggestion
    throw new Error(error.message);
```

2022-08-26 16:28 UTC, NikPaukov commented on src/services/user.service.ts
> +    if (result) {
whether i dont get it or it will return undefined if there is no result

2022-08-26 17:42 UTC, alexandrtovmach requested changes

2022-08-26 17:42 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +  }
don't use try catch

2022-08-26 17:42 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +      { ...data, updated_at: new Date().toISOString() }
```suggestion
      { ...data, updatedAt: new Date().toISOString() }
```

2022-08-26 19:24 UTC, VitaliiDenysyuk requested changes

2022-08-26 19:24 UTC, VitaliiDenysyuk commented on src/models/User.model.ts
> +  updated_at: Date | null;
```suggestion
  updated_at?: Date;
```

2022-08-26 19:24 UTC, VitaliiDenysyuk commented on src/models/User.model.ts
> +  location: string;
Is this field required?
```suggestion
  location?: string;
```

2022-08-26 19:24 UTC, VitaliiDenysyuk commented on src/models/User.model.ts
> +      type: Date,
```suggestion
      type: String,
```
you use toISOString() for this field

2022-08-26 19:24 UTC, VitaliiDenysyuk commented on src/routes/users.route.ts
> +});
remove try ...catch too

2022-08-28 13:14 UTC, alexandrtovmach approved these changes

2022-08-28 13:15 UTC, merged