feat: added yup validation
attech-org/leleka-backend pull request #12
Opened 2022-08-27 13:31 UTC by fominmaksim

- added yup and auth validation

2022-08-27 18:19 UTC, VitaliiDenysyuk requested changes
fix some mistakes

2022-08-27 18:19 UTC, VitaliiDenysiuk commented on src/helpers/validation.ts
> +});
```suggestion
export const registerSchema = loginSchema.concat(
  yup.object({
    email: yup
      .string()
      .required("Email can't be blank")
      .email("Please use a valid email address"),
  })
);
```
you duplicated big part of code.  use the closest thing to schema extension/inheritance in Yup

2022-08-27 18:19 UTC, VitaliiDenysyuk commented on src/helpers/validation.ts
> +
```suggestion
import { OptionalObjectSchema } from "yup/lib/object";
import { AnyObject } from "yup/lib/types";

export type AnyYupSchema = OptionalObjectSchema<AnyObject>;
```

such way we remove type "any" in middlewares

2022-08-27 18:19 UTC, VitaliiDenysyuk commented on src/middlewares/yup.middlewares.ts
> +
```suggestion
import { AnyYupSchema } from "../helpers/validation";
```

such way we remove type "any" in middlewares

2022-08-27 18:19 UTC, VitaliiDenysyuk commented on src/middlewares/yup.middlewares.ts
> +  (schema: any) => async (req: Request, res: Response, next: NextFunction) => {
```suggestion
  (schema: AnyYupSchema) =>
  async (req: Request, res: Response, next: NextFunction) => {
```

2022-08-28 13:24 UTC, VitaliiDenysyuk approved these changes
looks good to me

2022-08-31 16:30 UTC, alexandrtovmach approved these changes

2022-08-31 16:30 UTC, merged