Feature/login jwt
attech-org/leleka-backend pull request #2
Opened 2022-08-16 14:15 UTC by fominmaksim

2022-08-16 14:22 UTC, AndrewKaenko approved these changes

2022-08-16 15:51 UTC, alexandrtovmach requested changes
so far so good, but a few fixed required. Some of them related to @VitaliiDenysyuk part of changes, but please fix them in your PR

2022-08-16 15:51 UTC, alexandrtovmach commented on src/services/auth.service.ts
> +  return { user: userInDataBase, token: token };
```suggestion
  return { user: userInDataBase, accessToken: token };
```

2022-08-16 15:51 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +export const findUserByUserNameAndSelect = async (
why it should be in a separate method? is it reusing somewhere else except `findUserData`?

2022-08-16 15:51 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
>  export const findUserByUserName = async (username: string) => {
basically the same question to `findUserByUserName` method. I don't see any reasons to create it, and would suggest to keep this logic inside `findUserData` method

2022-08-16 15:51 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
>  export const findUserByUserName = async (username: string) => {
I know that's @VitaliiDenysyuk issue, but could you fix it in your PR?

2022-08-16 15:51 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +export const findUserData = async (user: User) => {
```suggestion
export const findUser = async (user: User) => {
```

2022-08-16 15:51 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
>  export const addUserData = async (user: User) => {
```suggestion
export const createUser = async (user: User) => {
```

2022-08-16 15:51 UTC, alexandrtovmach commented on src/routes/auth.route.ts
> +    if (error instanceof Error) {
@VitaliiDenysyuk affect 🤦 
please check our telegram chat, and use simple `error` without any `error.message`

2022-08-16 15:51 UTC, alexandrtovmach commented on src/routes/auth.route.ts
>      if (error instanceof Error) {
same

2022-08-16 19:24 UTC, VitaliiDenysyuk reviewed
take into account the suggestion of @alexandrtovmach, other looks good for me

2022-08-18 11:01 UTC, alexandrtovmach requested changes

2022-08-18 11:01 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +  if (user && username && password) {
wrong condition, because if `user` doesn't exist, then you'll have error on line 46

2022-08-18 11:01 UTC, alexandrtovmach commented on src/routes/auth.route.ts
> +    res.sendStatus(400);
why you not sending error message?

2022-08-18 11:01 UTC, alexandrtovmach commented on src/routes/auth.route.ts
> +    res.sendStatus(400);
why you not sending error message?

2022-08-18 11:05 UTC, alexandrtovmach requested changes

2022-08-18 11:05 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +    const getUserPassword = await UserModel.findOne({
```suggestion
    const userWIthPassword = await UserModel.findOne({
```

2022-08-18 11:05 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +      throw new Error("Password is incorrect");
```suggestion
      throw new Error("Wrong password");
```

2022-08-18 11:05 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +    if (!comparePassword(getUserPassword.password, password)) {
this logic should not be in repository, because it's "logic". All logic should be on service level

2022-08-18 17:00 UTC, alexandrtovmach requested changes

2022-08-18 17:00 UTC, alexandrtovmach commented on src/services/auth.service.ts
> +    }).select("password");
```
const userWithPassword = await userRepository.findUser(data, true);
```

in userRepository:

```
export const findUser = async (user: User, withPassword: boolean) => {
  const { username } = user;
  if (withPassword) {
      const userInDatabase = await UserModel.findOne({
        username: username,
      }).select("password");
      
      
      return userInDatabase;
    } else {
      const userInDatabase = await UserModel.findOne({ username: username });
      return userInDatabase;
    }
};
```

2022-08-19 16:53 UTC, VitaliiDenysyuk requested changes

2022-08-19 16:53 UTC, VitaliiDenysyuk commented on src/routes/auth.route.ts
> +  try {
return, please, block from develop. Exception catch in middlewares

2022-08-19 16:58 UTC, VitaliiDenysyuk requested changes

2022-08-19 16:58 UTC, VitaliiDenysyuk commented on src/routes/auth.route.ts
> +  }
```suggestion
  try {
    // process input data
    // call repository method
    const data = req.body;
    const result = await register(data);
    res.send(result);
  } catch (error: unknown) {
    console.error(error);
    return res.status(400).send(error.toString());
  }
```
return, please, block from develop. Exception catches in middlewares

2022-08-19 17:06 UTC, VitaliiDenysyuk commented on src/routes/auth.route.ts
> +  }
```suggestion
  }
```
You can remove try..catch now it catches in middlewares

2022-08-19 18:29 UTC, VitaliiDenysyuk approved these changes
Looks good for me

2022-08-20 19:03 UTC, alexandrtovmach approved these changes

2022-08-20 19:03 UTC, merged