Feature/add following
attech-org/leleka-backend pull request #23
Opened 2022-09-04 12:25 UTC by AndrewKaenko

2022-09-04 13:09 UTC, VitaliiDenysyuk requested changes

2022-09-04 13:09 UTC, VitaliiDenysiuk commented on src/repositories/following.repository.ts
> +};
```suggestion
export const getList = async (query: object, options: object) => {
  return FollowingModel.paginate(query, options);
};
```
check tweet repositories

2022-09-04 13:09 UTC, VitaliiDenysyuk commented on src/routes/following.route.ts
> +    const result = await getFollowing(req.query);
```suggestion
  .get(isAuthorized, async (req: Request, res: Response) => {
    const result = await getFollowing(new PaginationParameters(req));
```
 tweet router for example

2022-09-04 13:09 UTC, VitaliiDenysyuk commented on src/routes/following.route.ts
> +    res.sendStatus(200);
```suggestion
    const newFollowing = await addFollowing(req.body);
    res.status(201).send(newFollowing);
```
we need to return created object

2022-09-04 13:09 UTC, VitaliiDenysyuk commented on src/services/following.service.ts
> +};
```suggestion
export const getFollowing =  (queryParams: PaginationParameters<never, never>) => {
  return getList(...queryParams.get());
};
```
example in tweet service

2022-09-04 13:09 UTC, VitaliiDenysyuk commented on src/services/following.service.ts
> +export const addFollowing = async (data: Record<string, string>) => {
```suggestion
export const addFollowing =  (data: Record<string, string>) => {
```
why did you use async without await?

2022-09-04 13:09 UTC, VitaliiDenysyuk commented on src/services/following.service.ts
> +export const deleteFollowing = async (id: string) => {
```suggestion
export const deleteFollowing =  (id: string) => {
```
why did you use async without await?

2022-09-04 13:37 UTC, VitaliiDenysyuk requested changes

2022-09-04 13:37 UTC, VitaliiDenysyuk commented on src/models/Following.model.ts
> +  ownerId: mongoose.Schema.Types.ObjectId;
```suggestion
  followingId: Types.ObjectId;
  ownerId: Types.ObjectId;
```
https://mongoosejs.com/docs/typescript.html

2022-09-04 13:37 UTC, VitaliiDenysyuk commented on src/models/Following.model.ts
> +    type: mongoose.Schema.Types.ObjectId,
```suggestion
    type: Schema.Types.ObjectId,
```
https://mongoosejs.com/docs/typescript.html

2022-09-04 13:37 UTC, VitaliiDenysyuk commented on src/models/Following.model.ts
> +    type: mongoose.Schema.Types.ObjectId,
```suggestion
    type: Schema.Types.ObjectId,
```
https://mongoosejs.com/docs/typescript.html

2022-09-04 13:37 UTC, VitaliiDenysyuk commented on src/models/Following.model.ts
> +  createdAt: string;
```suggestion
  createdAt?: string;
```
we filled it by default

2022-09-04 14:59 UTC, VitaliiDenysyuk approved these changes
looks good to me

2022-09-05 20:48 UTC, alexandrtovmach approved these changes

2022-09-05 20:48 UTC, merged