feat:added Tag entity + CRUD + REST
attech-org/leleka-backend pull request #38
Opened 2022-09-07 18:59 UTC by VladislavPokhyl

2022-09-07 21:36 UTC, VitaliiDenysyuk requested changes

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/models/Tag.model.ts
> +  createdAt: string;
```suggestion
  createdAt?: string;
```
filled by default

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/repositories/tags.repository.ts
> +export const getById = async (tagId: string | ObjectId) => {
```suggestion
export const getById = async (tagId: string) => {
```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/repositories/tags.repository.ts
> +export const create = async (tagData: Partial<Tag>) => {
```suggestion
export const create = (tagData: Partial<Tag>) => {
```
not await - async  was not needed

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/repositories/tags.repository.ts
> +export const getList = async () => {
```suggestion
export const getList =  () => {
```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/repositories/tags.repository.ts
> +  tagId: string | ObjectId,
```suggestion
export const update =  (
  tagId: string ,
```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/repositories/tags.repository.ts
> +export const deleteById = async (tagId: string | ObjectId) => {
```suggestion
export const deleteById = (tagId: string) => {
```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/repositories/tags.repository.ts
> +import { ObjectId } from "mongoose";
```suggestion

```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/services/tags.service.ts
> +import { ObjectId } from "mongoose";
```suggestion

```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/services/tags.service.ts
> +export const getTagsList = async (): Promise<Array<Tag>> => {
```suggestion
export const getTagsList =  () => {
```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/services/tags.service.ts
> +export const getTagById = async (id: string | ObjectId): Promise<Tag> => {
```suggestion
export const getTagById = (id: string ) => {
```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/services/tags.service.ts
> +};
```suggestion
export const createTag = (tagData: Partial<Tag>) => {
  return create(tagData);
};
```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/services/tags.service.ts
> +};
```suggestion
export const updateTag = (
  id: string,
  newData: Partial<Tag>
) => {
  return update(id, newData);
};
```

2022-09-07 21:36 UTC, VitaliiDenysyuk commented on src/services/tags.service.ts
> +export const deleteTagById = async (id: ObjectId | string) => {
```suggestion
export const deleteTagById = async (id: string) => {
```

2022-09-09 22:53 UTC, alexandrtovmach requested changes
add pagintation to getList request

2022-09-09 23:13 UTC, VladislavPokhyl commented
![image](https://user-images.githubusercontent.com/49875865/189457495-05b23d47-8567-4201-bd4d-838730ea1f0c.png)

2022-09-10 00:26 UTC, alexandrtovmach approved these changes

2022-09-10 00:26 UTC, merged