feat : added hashtag creation alongside with tweet create/update
attech-org/leleka-backend pull request #51
Opened 2022-09-11 18:29 UTC by VladislavPokhyl

https://trello.com/c/37IwAWM6/113-add-tag-parsing-functionality-to-tweet-creation

2022-09-11 19:18 UTC, alexandrtovmach requested changes

2022-09-11 19:18 UTC, alexandrtovmach commented on src/services/tweets.service.ts
> +    if (hashtagsDiff) {
```suggestion
    if (hashtagsDiff.length) {
```

2022-09-11 19:18 UTC, alexandrtovmach commented on src/services/tags.service.ts
> +  });
You can optimize this algorithm:
1. Do attempt to update tag by name with new stats
2. If it's failed to update, create a new tag
3. If it's success you're done

In that way you don't need to make "find" request

2022-09-11 19:18 UTC, alexandrtovmach commented on src/repositories/tags.repository.ts
> +  }
Not sure for what do we need this "options"?

2022-09-11 19:46 UTC, VladislavPokhyl commented on src/services/tweets.service.ts
> +    if (hashtagsDiff) {
My omission.  I'll fix it. Thanks

2022-09-12 12:54 UTC, VitaliiDenysyuk requested changes
Very important moment:
does not take into account the situation when the tag is removed when editing a tweet

2022-09-12 12:54 UTC, VitaliiDenysyuk commented on src/services/tweets.service.ts
> +  if (createResult) {
what do you check here?
if error we did not come here
if object we had always true

2022-09-12 12:54 UTC, VitaliiDenysyuk commented on src/services/tweets.service.ts
> +  if (updateResult) {
what do you check here?
if error we did not come here
if object we had always true

2022-09-12 12:54 UTC, VitaliiDenysyuk commented on src/services/tweets.service.ts
> +    const hashtagsDiff = newHashtags.filter((x) => !oldHashtags.includes(x));
create normal name of variable.
What if we had some tags before but now delete it?
Check this situation too use function decrementStatsByName

2022-09-12 12:54 UTC, VitaliiDenysyuk commented on src/repositories/tags.repository.ts
> +export const incrementStatsByName = (name: string) => {
add function decrement 
When we created tweet with tag, but after that modificated it and removed some tags from tweet

2022-09-14 23:17 UTC, VitaliiDenysyuk requested changes

2022-09-14 23:17 UTC, VitaliiDenysyuk commented on src/services/tags.service.ts
> +      }
```suggestion
      if (!(await incrementStatsByName(name))) {
        await create({ name: name }, { initialIncrementStats: true });
      }
```

2022-09-15 17:42 UTC, alexandrtovmach approved these changes

2022-09-15 17:42 UTC, alexandrtovmach commented on src/repositories/tags.repository.ts
> +  }
make default stats tweet for Tag model as 1, and drop this logic

2022-09-15 17:57 UTC, merged

2022-09-15 17:57 UTC, DavidKorystov approved these changes