Feature/ first tests for routes
attech-org/leleka-backend pull request #52
Opened 2022-09-12 15:59 UTC by NikPaukov

2022-09-13 21:14 UTC, VitaliiDenysyuk requested changes
very good job done.
fix some remarks

2022-09-13 21:14 UTC, VitaliiDenysiuk commented on src/repositories/likes.repository.ts
> +  return LikeModel.findOneAndUpdate({ _id: id }, newData);
```suggestion
  return LikeModel.findOneAndUpdate({ _id: id }, newData, {
  new: true
});
```
You should set the new option to true to return the document after update was applied.
https://mongoosejs.com/docs/tutorials/findoneandupdate.html

2022-09-13 21:14 UTC, VitaliiDenysiuk commented on src/test/routes.test.ts
> +            password: "1234567",
You can have mistake with length of password here. if somebody change order of check

2022-09-13 21:14 UTC, VitaliiDenysiuk commented on src/test/routes.test.ts
> +            password: "1234567",
same

2022-09-13 21:14 UTC, VitaliiDenysiuk commented on src/test/routes.test.ts
> +            password: "1234567",
same

2022-09-13 21:14 UTC, VitaliiDenysiuk commented on src/test/routes.test.ts
> +          expect(resp.body.error).toEqual("invalid signature");
I check response:
{
    "error": "invalid token"
}

2022-09-13 21:14 UTC, VitaliiDenysyuk commented on src/test/routes.test.ts
> +          await register({
we can get problem if previous test was bad at position "delete" and such user was at database

2022-09-14 16:06 UTC, NikPaukov commented on src/test/routes.test.ts
> +          expect(resp.body.error).toEqual("invalid signature");
![image](https://user-images.githubusercontent.com/103951082/190205789-6c6d7c7f-581c-42b7-9802-590af4c58665.png)

2022-09-14 23:04 UTC, VitaliiDenysyuk commented on src/test/routes.test.ts
> +          expect(resp.body.error).toEqual("invalid signature");
it's meaning we can have two different error. If I remember well I added at the beginning of the token letter

2022-09-15 19:22 UTC, merged