feat: added file upload
attech-org/leleka-backend pull request #54
Opened 2022-09-13 17:38 UTC by fominmaksim

2022-09-13 17:40 UTC, alexandrtovmach approved these changes

2022-09-13 20:03 UTC, VitaliiDenysyuk requested changes

2022-09-13 20:03 UTC, VitaliiDenysiuk commented on src/repositories/user.repository.ts
> +    if (base64Image) {
wrong place.
if somebody send data with password and file: first block if..else will be work and all your logic will not work. Such way you will write at database all info from field avatar without any logic

2022-09-13 23:28 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +    if (base64Image) {
yeah, agree, that what I tried to understand on live review, but not get it

2022-09-13 23:32 UTC, alexandrtovmach commented on src/repositories/user.repository.ts
> +    if (base64Image) {
I believe that mongoose ignore field if it's undefined, and not updating it, so this code block can be refactored to:
```ts
await UserModel.updateOne(
  { _id: id },
  {
    ...data,
    updatedAt: new Date().toISOString(),
    password: data.password && hashPassword(data.password),
    profile: { avatar: file && file?.buffer.toString("base64") },
  }
);
```

@fominmaksim could you test this approach, including password change and avatar, and see if it works. Thanks

2022-09-14 23:00 UTC, VitaliiDenysyuk approved these changes
lgtm

2022-09-15 14:02 UTC, merged