Feature/refresh token functionality
attech-org/leleka-backend pull request #6
Opened 2022-08-22 09:21 UTC by VitaliiDenysyuk

2022-08-24 16:52 UTC, AndrewKaenko approved these changes

2022-08-24 16:52 UTC, AndrewKaenko commented on src/config/jwt.ts
> +  if (verifyPeyload._id !== findTokenInDatabase.userId) {
Spelling mistake - peyload -> payload

2022-08-24 16:52 UTC, AndrewKaenko commented on src/middlewares/isAuthorised.middlewares.ts
> +  // try {
Why this detail?

2022-08-24 18:56 UTC, VitaliiDenysyuk commented on src/config/jwt.ts
> +  if (verifyPeyload._id !== findTokenInDatabase.userId) {
corrected

2022-08-24 18:56 UTC, VitaliiDenysyuk commented on src/middlewares/isAuthorised.middlewares.ts
> +  // try {
remove

2022-08-25 09:12 UTC, fominmaksim approved these changes
lgtm

2022-08-26 16:36 UTC, alexandrtovmach requested changes

2022-08-26 16:36 UTC, alexandrtovmach commented on src/middlewares/isAuthorised.middlewares.ts
> +import { NextFunction, Response, Request } from "express";
isAuthorized

2022-08-26 16:36 UTC, alexandrtovmach commented on src/middlewares/isAuthorised.middlewares.ts
> +  status: 403,
```suggestion
  status: 401,
```

2022-08-26 16:36 UTC, alexandrtovmach commented on src/routes/auth.route.ts
> +authRouter.route("/refreshToken").post(async (req: Request, res: Response) => {
```suggestion
authRouter.route("/refresh").post(async (req: Request, res: Response) => {
```

2022-08-26 17:10 UTC, alexandrtovmach approved these changes

2022-08-26 17:26 UTC, alexandrtovmach approved these changes

2022-08-26 17:26 UTC, merged