added following count func
attech-org/leleka-backend pull request #68
Opened 2022-09-19 17:16 UTC by DavidKorystov

2022-09-19 19:32 UTC, VitaliiDenysyuk requested changes

2022-09-19 19:32 UTC, VitaliiDenysyuk commented on src/repositories/user.repository.ts
> +  return UserModel.updateOne({ _id: id }, { $inc: { [fieldName]: value } });
```suggestion
  return UserModel.findOneAndUpdate({ _id: id }, { $inc: { [fieldName]: value } },{
  new: true
});
```
https://mongoosejs.com/docs/tutorials/findoneandupdate.html

2022-09-19 19:32 UTC, VitaliiDenysyuk commented on src/services/followers.service.ts
> +    throw new Error("You can't subscribe to your self");
```suggestion
    throw new Error("You can't subscribe to yourself");
```

2022-09-20 05:36 UTC, VitaliiDenysyuk approved these changes
lgtm

2022-09-20 13:58 UTC, alexandrtovmach approved these changes

2022-09-20 13:59 UTC, merged