Feat/added stats to user model
attech-org/leleka-backend pull request #71
Opened 2022-09-21 15:34 UTC by DavidKorystov

2022-09-21 17:37 UTC, VitaliiDenysyuk requested changes

2022-09-21 17:37 UTC, VitaliiDenysiuk commented on src/models/User.model.ts
> +      followingCount: Number,
add default values
otherwise we will get null for the newly created user and there will be an error of adding 1 to null

2022-09-21 17:53 UTC, VitaliiDenysyuk requested changes

2022-09-21 17:53 UTC, VitaliiDenysyuk commented on src/models/User.model.ts
> +  stats: {
you need to warn the frontend about changing the structure

2022-09-22 05:31 UTC, VitaliiDenysyuk approved these changes
lgtm

2022-09-22 17:53 UTC, alexandrtovmach approved these changes

2022-09-22 17:53 UTC, merged