fix/delete-bookmark-by-tweet&owner
attech-org/leleka-backend pull request #80
Opened 2022-09-29 20:58 UTC by NikPaukov

2022-09-29 21:06 UTC, DavidKorystov requested changes

2022-09-29 21:06 UTC, DavidKorystov commented on src/routes/bookmarks.route.ts
>    .delete(isAuthorized, validation(deleteBookmarkById), async (req, res) => {
I think this route already unnecessary, bcs deleting by tweetId is enough.

2022-09-29 21:07 UTC, DavidKorystov commented on src/routes/bookmarks.route.ts
>    .delete(isAuthorized, validation(deleteBookmarkById), async (req, res) => {
@alexandrtovmach

2022-09-29 21:25 UTC, VitaliiDenysyuk requested changes
you PR had problem.

![image](https://user-images.githubusercontent.com/103836064/193145194-19a74166-3c49-4949-a245-f1df8cfc6c8b.png)

 Clean all console.log

2022-09-30 13:29 UTC, VitaliiDenysyuk approved these changes
lgtm

2022-09-30 16:31 UTC, merged